// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/MihaFriskovec/3fs-assignment/models"
)

// ListGroupsOKCode is the HTTP code returned for type ListGroupsOK
const ListGroupsOKCode int = 200

/*ListGroupsOK List all groups

swagger:response listGroupsOK
*/
type ListGroupsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Group `json:"body,omitempty"`
}

// NewListGroupsOK creates ListGroupsOK with default headers values
func NewListGroupsOK() *ListGroupsOK {

	return &ListGroupsOK{}
}

// WithPayload adds the payload to the list groups o k response
func (o *ListGroupsOK) WithPayload(payload []*models.Group) *ListGroupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups o k response
func (o *ListGroupsOK) SetPayload(payload []*models.Group) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Group, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListGroupsBadRequestCode is the HTTP code returned for type ListGroupsBadRequest
const ListGroupsBadRequestCode int = 400

/*ListGroupsBadRequest User error

swagger:response listGroupsBadRequest
*/
type ListGroupsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListGroupsBadRequest creates ListGroupsBadRequest with default headers values
func NewListGroupsBadRequest() *ListGroupsBadRequest {

	return &ListGroupsBadRequest{}
}

// WithPayload adds the payload to the list groups bad request response
func (o *ListGroupsBadRequest) WithPayload(payload *models.Error) *ListGroupsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups bad request response
func (o *ListGroupsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListGroupsInternalServerErrorCode is the HTTP code returned for type ListGroupsInternalServerError
const ListGroupsInternalServerErrorCode int = 500

/*ListGroupsInternalServerError Server error

swagger:response listGroupsInternalServerError
*/
type ListGroupsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListGroupsInternalServerError creates ListGroupsInternalServerError with default headers values
func NewListGroupsInternalServerError() *ListGroupsInternalServerError {

	return &ListGroupsInternalServerError{}
}

// WithPayload adds the payload to the list groups internal server error response
func (o *ListGroupsInternalServerError) WithPayload(payload *models.Error) *ListGroupsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups internal server error response
func (o *ListGroupsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListGroupsDefault Unknown error

swagger:response listGroupsDefault
*/
type ListGroupsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListGroupsDefault creates ListGroupsDefault with default headers values
func NewListGroupsDefault(code int) *ListGroupsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListGroupsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list groups default response
func (o *ListGroupsDefault) WithStatusCode(code int) *ListGroupsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list groups default response
func (o *ListGroupsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list groups default response
func (o *ListGroupsDefault) WithPayload(payload *models.Error) *ListGroupsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups default response
func (o *ListGroupsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
